#!/usr/bin/env python3
"""Run rolling-season backtests for series prediction model variants."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd
from sklearn.metrics import accuracy_score, brier_score_loss, log_loss, roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

PROJECT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_DIR))

from src.series_context_features import (  # noqa: E402
    SERIES_BASE_FEATURE_COLS,
    SERIES_CONTEXT_MODEL_FEATURE_COLS,
    add_series_context_features,
)
from src.series_training import add_series_start_dates  # noqa: E402


MODEL_CONFIGS = {
    "baseline_xgb": {
        "features": "base",
        "params": {
            "n_estimators": 200,
            "max_depth": 4,
            "learning_rate": 0.05,
            "subsample": 0.8,
            "random_state": 42,
            "eval_metric": "logloss",
        },
    },
    "context_xgb_regularized": {
        "features": "context",
        "params": {
            "n_estimators": 60,
            "max_depth": 2,
            "learning_rate": 0.03,
            "subsample": 0.8,
            "colsample_bytree": 0.8,
            "reg_lambda": 5,
            "random_state": 42,
            "eval_metric": "logloss",
        },
    },
    "context_xgb_stump": {
        "features": "context",
        "params": {
            "n_estimators": 50,
            "max_depth": 1,
            "learning_rate": 0.05,
            "subsample": 0.9,
            "colsample_bytree": 0.8,
            "reg_lambda": 5,
            "random_state": 42,
            "eval_metric": "logloss",
        },
    },
    "context_xgb_strong_reg": {
        "features": "context",
        "params": {
            "n_estimators": 100,
            "max_depth": 2,
            "learning_rate": 0.02,
            "subsample": 0.8,
            "colsample_bytree": 0.7,
            "reg_lambda": 10,
            "reg_alpha": 1,
            "random_state": 42,
            "eval_metric": "logloss",
        },
    },
    "context_xgb_logloss": {
        "features": "context",
        "params": {
            "n_estimators": 120,
            "max_depth": 3,
            "learning_rate": 0.02,
            "subsample": 0.8,
            "colsample_bytree": 0.6,
            "reg_lambda": 20,
            "reg_alpha": 1,
            "random_state": 42,
            "eval_metric": "logloss",
        },
    },
}


def build_model(params: dict) -> Pipeline:
    from xgboost import XGBClassifier

    return Pipeline([
        ("scaler", StandardScaler()),
        ("clf", XGBClassifier(**params)),
    ])


def score_model(model: Pipeline, X: pd.DataFrame, y: pd.Series) -> dict[str, float]:
    prob = model.predict_proba(X)[:, 1]
    pred = (prob >= 0.5).astype(int)
    return {
        "accuracy": float(accuracy_score(y, pred)),
        "roc_auc": float(roc_auc_score(y, prob)),
        "log_loss": float(log_loss(y, prob)),
        "brier_score": float(brier_score_loss(y, prob)),
    }


def backtest_variant(df: pd.DataFrame, seasons: list[str], name: str, config: dict, min_train_seasons: int) -> list[dict]:
    feature_cols = SERIES_BASE_FEATURE_COLS if config["features"] == "base" else SERIES_CONTEXT_MODEL_FEATURE_COLS
    rows = []
    for idx in range(min_train_seasons, len(seasons)):
        test_season = seasons[idx]
        train_seasons = seasons[:idx]
        train = df[df["season"].isin(train_seasons)]
        test = df[df["season"] == test_season]
        if train.empty or test.empty:
            continue
        model = build_model(config["params"])
        model.fit(train[feature_cols], train["higher_seed_wins"])
        metrics = score_model(model, test[feature_cols], test["higher_seed_wins"])
        rows.append({
            "model": name,
            "feature_set": config["features"],
            "test_season": test_season,
            "train_seasons": len(train_seasons),
            "test_rows": len(test),
            "higher_seed_baseline": float(test["higher_seed_wins"].mean()),
            **metrics,
        })
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--features",
        type=Path,
        default=PROJECT_DIR / "data" / "processed" / "series_features.parquet",
        help="Series feature parquet generated by notebook 03b.",
    )
    parser.add_argument(
        "--min-train-seasons",
        type=int,
        default=5,
        help="Minimum number of seasons before first rolling test.",
    )
    parser.add_argument(
        "--out-csv",
        type=Path,
        default=PROJECT_DIR / "outputs" / "model_reports" / "series_backtest_by_season.csv",
    )
    parser.add_argument(
        "--out-json",
        type=Path,
        default=PROJECT_DIR / "outputs" / "model_reports" / "series_backtest_summary.json",
    )
    args = parser.parse_args()

    df = pd.read_parquet(args.features)
    df = add_series_start_dates(df)
    df = add_series_context_features(df)
    seasons = sorted(df["season"].unique())

    rows = []
    for name, config in MODEL_CONFIGS.items():
        rows.extend(backtest_variant(df, seasons, name, config, args.min_train_seasons))

    results = pd.DataFrame(rows)
    summary = (
        results.groupby("model")
        .agg(
            seasons=("test_season", "count"),
            test_rows=("test_rows", "sum"),
            accuracy=("accuracy", "mean"),
            roc_auc=("roc_auc", "mean"),
            log_loss=("log_loss", "mean"),
            brier_score=("brier_score", "mean"),
            higher_seed_baseline=("higher_seed_baseline", "mean"),
        )
        .sort_values(["roc_auc", "log_loss"], ascending=[False, True])
        .reset_index()
    )

    args.out_csv.parent.mkdir(parents=True, exist_ok=True)
    results.to_csv(args.out_csv, index=False)
    with args.out_json.open("w") as f:
        json.dump({
            "min_train_seasons": args.min_train_seasons,
            "season_results_path": str(args.out_csv),
            "summary": summary.to_dict(orient="records"),
        }, f, indent=2)
        f.write("\n")

    print("Rolling backtest summary:")
    print(summary.to_string(index=False, float_format=lambda x: f"{x:.4f}"))
    print(f"Wrote {args.out_csv}")
    print(f"Wrote {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
