#!/usr/bin/env python3
"""Retrain series XGBoost with derived context features."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd
from sklearn.metrics import accuracy_score, brier_score_loss, log_loss, roc_auc_score

PROJECT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_DIR))

from src.models import (  # noqa: E402
    build_regularized_xgboost_pipeline,
    build_xgboost_pipeline,
    save_model,
    train_test_split_by_season,
)
from src.series_context_features import (  # noqa: E402
    SERIES_BASE_FEATURE_COLS,
    SERIES_CONTEXT_MODEL_FEATURE_COLS,
    add_series_context_features,
)
from src.series_training import add_series_start_dates  # noqa: E402


def evaluate(model, X: pd.DataFrame, y: pd.Series) -> dict[str, float]:
    pred = model.predict(X)
    prob = model.predict_proba(X)[:, 1]
    return {
        "accuracy": round(float(accuracy_score(y, pred)), 4),
        "roc_auc": round(float(roc_auc_score(y, prob)), 4),
        "log_loss": round(float(log_loss(y, prob)), 4),
        "brier_score": round(float(brier_score_loss(y, prob)), 4),
    }


def fit_and_score(
    df: pd.DataFrame,
    feature_cols: list[str],
    test_seasons: list[str],
    regularized: bool = False,
) -> tuple[object, dict]:
    train_df, test_df = train_test_split_by_season(df, test_seasons)
    X_train = train_df[feature_cols]
    y_train = train_df["higher_seed_wins"]
    X_test = test_df[feature_cols]
    y_test = test_df["higher_seed_wins"]

    model = build_regularized_xgboost_pipeline() if regularized else build_xgboost_pipeline()
    model.fit(X_train, y_train)

    metrics = evaluate(model, X_test, y_test)
    metrics["features"] = len(feature_cols)
    metrics["train_rows"] = len(train_df)
    metrics["test_rows"] = len(test_df)
    metrics["test_higher_seed_win_rate"] = round(float(y_test.mean()), 4)
    return model, metrics


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--features",
        type=Path,
        default=PROJECT_DIR / "data" / "processed" / "series_features.parquet",
        help="Series feature parquet generated by notebook 03b.",
    )
    parser.add_argument(
        "--test-seasons",
        nargs="+",
        default=["2022-23", "2023-24"],
        help="Holdout seasons for temporal evaluation.",
    )
    parser.add_argument(
        "--model-name",
        default="series_xgboost_context",
        help="Saved model name without .joblib.",
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=PROJECT_DIR / "outputs" / "model_reports" / "series_xgboost_context.json",
        help="Where to write holdout metrics.",
    )
    args = parser.parse_args()

    df = pd.read_parquet(args.features)
    df = add_series_start_dates(df)
    df_context = add_series_context_features(df)
    context_features = list(SERIES_CONTEXT_MODEL_FEATURE_COLS)

    baseline_model, baseline_metrics = fit_and_score(df_context, SERIES_BASE_FEATURE_COLS, args.test_seasons)
    context_model, context_metrics = fit_and_score(
        df_context,
        context_features,
        args.test_seasons,
        regularized=True,
    )

    saved_path = save_model(context_model, args.model_name)

    report = {
        "test_seasons": args.test_seasons,
        "baseline_model": "series_xgboost",
        "baseline_estimator": "default_xgboost",
        "context_model": args.model_name,
        "context_estimator": "regularized_xgboost",
        "saved_path": str(saved_path),
        "baseline_metrics": baseline_metrics,
        "context_metrics": context_metrics,
        "context_features": context_features,
    }

    args.report.parent.mkdir(parents=True, exist_ok=True)
    with args.report.open("w") as f:
        json.dump(report, f, indent=2)
        f.write("\n")

    print("Baseline XGBoost:", baseline_metrics)
    print("Context  XGBoost:", context_metrics)
    print(f"Saved context model -> {saved_path}")
    print(f"Wrote report -> {args.report}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
